// lib/ai/advanced-ai-detector.ts - FIXED WITH REAL AI DETECTION (SAME FUNCTION NAMES)
import { smartAIProvider } from './smart-provider-manager';

export interface AIDetectionResult {
  humanLikeScore: number; // 0-100 (inverse of AI score)
  aiLikelihood: string; // "Very High (95%)" etc
  aiLikelihoodPercent: number; // Main AI percentage score (0-100)
  confidenceLevel: number; // 0-100
  analysis: string;
  riskLevel: string; // "CRITICAL RISK" etc
  indicators: string[];
  detectionMethod: string;
}

export class AdvancedAIDetector {
  static async detectAIContent(
    content: string,
    options: {
      childAge?: number;
      expectedGenre?: string;
      isCreativeWriting?: boolean;
    } = {}
  ): Promise<AIDetectionResult> {
    console.log('🔍 Starting AI-powered detection analysis...');

    // REPLACE ALL FAKE LOCAL DETECTION WITH SINGLE AI CALL
    const detectionResults = await Promise.all([
      this.performPatternAnalysis(content, options),
      this.performLinguisticAnalysis(content, options),
      this.performAIProviderAnalysis(content, options),
      this.performStatisticalAnalysis(content, options),
    ]);

    // Combine results with weighted scoring
    const finalScore = this.combineDetectionResults(detectionResults);

    console.log(
      `🤖 AI Detection: ${finalScore.aiLikelihood} (${finalScore.aiLikelihoodPercent}% AI likelihood)`
    );

    return finalScore;
  }

  // REPLACE: Now uses AI instead of regex patterns
  private static async performPatternAnalysis(content: string, options: any) {
    try {
      const result = await this.callAIForDetection(content, options, 'pattern_analysis');
      return result;
    } catch (error) {
      console.error('Pattern analysis failed, using fallback');
      return { aiScore: 15, indicators: ['Pattern analysis unavailable'], method: 'pattern_analysis' };
    }
  }

  // REPLACE: Now uses AI instead of fake linguistic analysis
  private static async performLinguisticAnalysis(content: string, options: any) {
    try {
      const result = await this.callAIForDetection(content, options, 'linguistic_analysis');
      return result;
    } catch (error) {
      console.error('Linguistic analysis failed, using fallback');
      return { aiScore: 10, indicators: ['Linguistic analysis unavailable'], method: 'linguistic_analysis' };
    }
  }

  // REPLACE: Now actually uses AI provider for detection
  private static async performAIProviderAnalysis(content: string, options: any) {
    try {
      const result = await this.callAIForDetection(content, options, 'ai_provider_analysis');
      return result;
    } catch (error) {
      console.error('AI provider analysis failed, using fallback');
      return { aiScore: 20, indicators: ['AI provider analysis unavailable'], method: 'ai_provider_analysis' };
    }
  }

  // REPLACE: Now uses AI instead of fake statistical analysis
  private static async performStatisticalAnalysis(content: string, options: any) {
    try {
      const result = await this.callAIForDetection(content, options, 'statistical_analysis');
      return result;
    } catch (error) {
      console.error('Statistical analysis failed, using fallback');
      return { aiScore: 5, indicators: ['Statistical analysis unavailable'], method: 'statistical_analysis' };
    }
  }

  // NEW: Single AI call that replaces all the fake detection methods
  private static async callAIForDetection(content: string, options: any, analysisType: string) {
    const childAge = options.childAge || 10;
    const expectedGenre = options.expectedGenre || 'creative';
    
    const detectionPrompt = `
Analyze this text to determine if it was written by a human child (age ${childAge}) or generated by AI.

TEXT: "${content}"

CONTEXT:
- Writer age: ${childAge} years old  
- Expected genre: ${expectedGenre}
- Analysis focus: ${analysisType}

EVALUATION CRITERIA:
1. Language patterns (natural vs artificial)
2. Age-appropriate vocabulary and complexity  
3. Authentic child voice vs generic AI style
4. Writing patterns typical of AI generation
5. Sentence structure and flow
6. Creative authenticity

IMPORTANT: Be balanced and fair. Many children are creative writers. Don't penalize genuine creativity.

Rate the AI likelihood from 0-100 (0 = definitely human, 100 = definitely AI).
Consider that this is a ${childAge}-year-old's creative writing.

Respond ONLY with this JSON:
{
  "aiScore": <0-100>,
  "confidence": <0-100>,
  "reasoning": "<brief explanation>",
  "indicators": ["<indicator1>", "<indicator2>"],
  "humanLikeElements": ["<human element1>", "<human element2>"]
}`;

    const response = await smartAIProvider.generateResponse(detectionPrompt);
    const cleanedResponse = response.replace(/```json|```/g, '').trim();
    const result = JSON.parse(cleanedResponse);
    
    return {
      aiScore: Math.min(100, Math.max(0, result.aiScore || 0)),
      indicators: result.indicators || ['AI analysis completed'],
      confidence: result.confidence || 75,
      method: analysisType,
      reasoning: result.reasoning || '',
      humanElements: result.humanLikeElements || []
    };
  }

  // KEEP: Same function name, but fix the logic
  private static combineDetectionResults(results: any[]): AIDetectionResult {
    console.log('🔬 Combining AI-based detection results...');

    // Equal weights for all analysis types
    const weights = {
      pattern_analysis: 0.25,
      linguistic_analysis: 0.25, 
      ai_provider_analysis: 0.25,
      statistical_analysis: 0.25,
    };

    let totalScore = 0;
    let allIndicators: string[] = [];
    let confidence = 0;
    let allHumanElements: string[] = [];

    results.forEach((result) => {
      const weight = weights[result.method as keyof typeof weights] || 0.25;
      totalScore += (result.aiScore || 0) * weight;
      allIndicators.push(...(result.indicators || []));
      confidence += (result.confidence || 0) * weight;
      if (result.humanElements) {
        allHumanElements.push(...result.humanElements);
      }
    });

    totalScore = Math.min(100, Math.max(0, Math.round(totalScore)));
    confidence = Math.min(100, Math.max(0, Math.round(confidence)));

    // BALANCED THRESHOLDS (not overly aggressive)
    let aiLikelihoodText: string;
    let riskLevel: string;
    const aiLikelihoodPercent = totalScore;

    if (totalScore >= 80) {
      aiLikelihoodText = `Very High (${aiLikelihoodPercent}%)`;
      riskLevel = 'CRITICAL RISK';
    } else if (totalScore >= 60) {
      aiLikelihoodText = `High (${aiLikelihoodPercent}%)`;
      riskLevel = 'HIGH RISK';
    } else if (totalScore >= 40) {
      aiLikelihoodText = `Medium (${aiLikelihoodPercent}%)`;
      riskLevel = 'MEDIUM RISK';
    } else if (totalScore >= 20) {
      aiLikelihoodText = `Low (${aiLikelihoodPercent}%)`;
      riskLevel = 'LOW RISK';
    } else {
      aiLikelihoodText = `Very Low (${aiLikelihoodPercent}%)`;
      riskLevel = 'VERY LOW RISK';
    }

    let analysis: string;
    if (totalScore >= 80) {
      analysis = 'Strong indicators suggest this content was likely generated by AI rather than written by a human child.';
    } else if (totalScore >= 60) {
      analysis = 'Several patterns suggest possible AI assistance or generation.';
    } else if (totalScore >= 40) {
      analysis = 'Some AI-like characteristics present, but could be sophisticated human writing.';
    } else if (totalScore >= 20) {
      analysis = 'Mostly appears human-written with some minor concerns.';
    } else {
      analysis = 'Content appears to be authentically human-written.';
    }

    // Add human elements to indicators for balance
    if (allHumanElements.length > 0) {
      allIndicators.push(`Human-like elements: ${allHumanElements.slice(0, 3).join(', ')}`);
    }

    // Calculate human-like score (inverse of AI score)
    const humanLikeScore = Math.max(0, 100 - aiLikelihoodPercent);

    return {
      humanLikeScore: Math.round(humanLikeScore),
      aiLikelihood: aiLikelihoodText,
      aiLikelihoodPercent: aiLikelihoodPercent,
      confidenceLevel: Math.round(confidence),
      analysis,
      riskLevel,
      indicators: [...new Set(allIndicators)].slice(0, 8), // Remove duplicates, limit to 8
      detectionMethod: 'AI-Powered Detection System',
    };
  }
}